config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :projects do
    resources :members
    resources :discussions
  end

  delete 'members/destroy' => "members#destroy"
  post 'members/edit' => "members#edit"
  # get 'pages/home'
  get 'login', to: 'pages#login'
  # get 'pages/login'
  # get 'pages/register'
  get 'register', to: 'pages#register'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :project
  
    
  end
  

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :authenticate_user!

    def index
        @members = show_members
    end

    def show

    end

    def new
        @member = Role.new
        redirect_to projects_path
    end

    def edit
        user = User.find(changeRole[:id])
        project = Project.find(changeRole[:project_id])

        if (changeRole[:is_admin] == "1")
            user.remove_role :member, project 
            user.add_role :member_admin, project 
        else
            user.remove_role :member_admin, project 
            user.add_role :member, project 
        end

        redirect_to request.referer
    end

    def create
        @user = User.find_by(email: project_params[:email])
        project = Project.find(params[:project_id])

        return redirect_to request.referer, alert: "User with this name does not exist!" if @user.nil?
        
        if (@user.has_role? :member, project or 
            @user.has_role? :member_admin, project or 
            @user.has_role? :creator, project)
            redirect_to request.referer, alert: "User with this name already exist!"
        else
            if project_params[:is_admin] == '1'
                @user.add_role :member_admin, project
                redirect_to project_members_path
            else
                @user.add_role :member, project
                redirect_to project_members_path
            end
        end
    end

    def update
        redirect_to request.referer
    end

    def destroy
        user = User.find(destroy_params[:id])
        project = Project.find(destroy_params[:project_id])
        if(user.has_role? :member, project)
            user.remove_role :member, project 
        else
            user.remove_role :member_admin, project 
        end
        redirect_to request.referer
    end

    private

    def project_params
        params.require(:member).permit(:email, :is_admin)
    end

    def destroy_params
        params.require(:destroy).permit(:id, :project_id)
    end

    def changeRole
        params.require(:changeRole).permit(:id, :project_id, :is_admin)
    end
    
    def show_members 
        @project = Project.find(params[:project_id])
        User.with_any_role(:member, { name: :member, resource: @project }, { name: :member_admin, resource: @project })
    end
end

app/views/members/_changeRole.html.erb
<div class="form-check form-switch">
    <% if item.has_role? :member, Project.find(params[:project_id])%>
        <%= form.check_box :is_admin, class: "form-check-input", onchange: "this.form.submit();"%>
    <% else %>
        <%= form.check_box :is_admin, checked: true ,class: "form-check-input", onchange: "this.form.submit();"%>
    <% end %>
    <%= form.label "Admin", class: "form-check-label" %>
</div>

app/views/members/_form.html.erb
<%= form_for :member, url: project_members_path(params[:id]) do |form| %>
    <div class="field mt-5">
        <%= form.label 'Add Member (email)', style: "display: block" %>
        <%= form.text_field :email, :required => true, class: "form-control" %>
        <div class="form-check form-switch">
            <%= form.check_box :is_admin, class: "form-check-input"%>
            <%= form.label "Make Admin", class: "form-check-label" %>
        </div>

    <div class="d-flex text-center justify-content-between">
        <%= form.submit "Add Member", :class => 'btn btn-success' %>
        <%= link_to "Show Members", project_members_path(params[:id]), class: "btn btn-warning ml-5" %>
    </div>
<% end %>

app/views/members/_formMembers.html.erb
<div class="d-flex align-items-center">
    <%= form_for :destroy, url: members_destroy_path, method: :delete do |form| %>
        <%= form.hidden_field  :id, value: item.id %>
        <%= form.hidden_field  :project_id, value: params[:project_id]%>
        <%= form.submit "Delete", class: "btn btn-danger", style: "margin-right: 10px;" %>
    <% end %>
    <%= form_for :changeRole, url: members_edit_path, method: :post do |form| %>
        <%= form.hidden_field  :id, value: item.id,  class: "form-control" %>
        <%= form.hidden_field  :project_id, value: params[:project_id]%>
        <div class="form-check form-switch">
            <% if item.has_role? :member, Project.find(params[:project_id])%>
                <%= form.check_box :is_admin, class: "form-check-input", onchange: "this.form.submit();"%>
            <% else %>
                <%= form.check_box :is_admin, checked: true ,class: "form-check-input", onchange: "this.form.submit();"%>
            <% end %>
            <%= form.label "Admin", class: "form-check-label" %>
        </div>
    <% end %>
</div>

app/views/members/index.html.erb
<% content_for :title do %>
    Members
<% end %>
<div class="row">
    <div class="my-3 p-3 bg-white rounded box-shadow">
        <h6 class="border-bottom border-gray pb-2 mb-0">Project members</h6>
        <% @members.each do |item| %>
            <div class="media text-muted pt-3">
                <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
                    <div class="d-flex justify-content-between align-items-center w-100">
                        <strong class="text-gray-dark"><%= item.name %></strong>
                        <%= render  "formMembers", item: item %>
                    </div>
                    <span class="d-block"><%= item.email %></span>
                </div>
            </div>
        <% end %>
    </div>
</div>

app/views/members/new.html.erb
<%= render "form" %>